import type { CrmFeedItem } from "@/lib/crm-feed";
import { PLUMBING_DEMO_BUSINESS_NAME } from "@/lib/voice-demo-plumbing-constants";

const BIZ = PLUMBING_DEMO_BUSINESS_NAME;

/** Fictional Metro Plumbing CRM activity - never written to production tables. */
export function getPlumbingDemoCrmSeedItems(): CrmFeedItem[] {
  const items: CrmFeedItem[] = [
    {
      id: "demo-contact-1",
      source: "contact",
      at: "2026-06-08T14:22:00.000Z",
      title: "Maria Torres",
      email: "mtorres@example.com",
      businessName: "Torres Family - Montclair, NJ",
      status: null,
      notes: null,
      stripeSessionId: null,
      stripeSubscriptionId: null,
      message:
        "Basement sump pump running constantly after last night’s storm. Is someone available today?",
      phone: "(973) 555-0142",
      contact: { cellPhone: "(973) 555-0142", city: "Montclair", state: "NJ" },
      payload: null,
      readAt: null,
      inboxFlag: "alert",
    },
    {
      id: "demo-contact-2",
      source: "contact",
      at: "2026-06-07T19:05:00.000Z",
      title: "James Wei",
      email: "j.wei@northsideproperties.example",
      businessName: "Northside Property Mgmt",
      status: null,
      notes: "Asked about commercial maintenance contract for 6-unit building.",
      stripeSessionId: null,
      stripeSubscriptionId: null,
      message: "Looking for quarterly drain maintenance across six units in Hackensack.",
      phone: "(201) 555-8831",
      contact: { cellPhone: "(201) 555-8831", city: "Hackensack", state: "NJ", zip: "07601" },
      payload: null,
      readAt: null,
      inboxFlag: null,
    },
    {
      id: "demo-lead-1",
      source: "lead",
      at: "2026-06-08T16:40:00.000Z",
      title: "Sarah Klein",
      email: "sarah.klein@example.com",
      businessName: "Klein Residence - Ridgewood, NJ",
      status: "deposit_paid",
      notes: "Jarvis booked water heater replacement - 40 gal gas, attic install.",
      stripeSessionId: null,
      stripeSubscriptionId: null,
      message: "Water heater replacement · Thu Jun 12 · 9–11 AM window",
      phone: "(201) 555-2290",
      contact: {
        cellPhone: "(201) 555-2290",
        street: "42 Oak Street",
        city: "Ridgewood",
        state: "NJ",
        zip: "07450",
      },
      payload: {
        hostingChoice: "monthly",
        addons: ["jarvis-voice"],
        designPromo: null,
      },
      readAt: null,
      inboxFlag: "star",
    },
    {
      id: "demo-lead-2",
      source: "lead",
      at: "2026-06-08T11:15:00.000Z",
      title: "David Okonkwo",
      email: "d.okonkwo@example.com",
      businessName: "Okonkwo Home - Teaneck, NJ",
      status: "awaiting_deposit",
      notes: null,
      stripeSessionId: null,
      stripeSubscriptionId: null,
      message: "Emergency leak under kitchen sink - callback requested after voice demo.",
      phone: "(551) 555-4401",
      contact: { cellPhone: "(551) 555-4401" },
      payload: { source: "jarvis_voice_demo" },
      readAt: null,
      inboxFlag: null,
    },
    {
      id: "demo-client-1",
      source: "client",
      at: "2026-06-05T09:00:00.000Z",
      title: "Robert & Sons Mechanical",
      email: "dispatch@robertssons.example",
      businessName: "Robert & Sons Mechanical",
      status: "paid_in_full",
      notes: "Commercial client - quarterly backflow testing. Next visit Sep 2026.",
      stripeSessionId: null,
      stripeSubscriptionId: null,
      message: "Active client · backflow certification on file",
      phone: "(973) 555-7710",
      contact: {
        cellPhone: "(973) 555-7710",
        street: "880 Industrial Park Drive",
        line2: "Suite 12",
        city: "Paterson",
        state: "NJ",
        zip: "07514",
      },
      payload: { hostingChoice: "ten_year" },
      readAt: null,
      inboxFlag: "check",
    },
    {
      id: "demo-sms-1",
      source: "sms",
      at: "2026-06-08T17:02:00.000Z",
      title: "(862) 555-9033",
      email: "",
      businessName: BIZ,
      status: null,
      notes: null,
      stripeSessionId: null,
      stripeSubscriptionId: null,
      message: "Can you move my appointment from Thursday to Friday afternoon?",
      phone: "(862) 555-9033",
      contact: {
        cellPhone: "(862) 555-9033",
        street: "15 Linden Avenue",
        city: "West Orange",
        state: "NJ",
        zip: "07052",
      },
      payload: { direction: "inbound", body: "Can you move my appointment from Thursday to Friday afternoon?" },
      readAt: null,
      inboxFlag: null,
    },
    {
      id: "demo-sms-2",
      source: "sms",
      at: "2026-06-07T08:44:00.000Z",
      title: "(914) 555-1188",
      email: "",
      businessName: BIZ,
      status: null,
      notes: null,
      stripeSessionId: null,
      stripeSubscriptionId: null,
      message: "Thanks - tech was great yesterday. Leaving a Google review tonight.",
      phone: "(914) 555-1188",
      contact: { cellPhone: "(914) 555-1188" },
      payload: { direction: "inbound" },
      readAt: null,
      inboxFlag: null,
    },
    {
      id: "demo-discovery-1",
      source: "discovery",
      at: "2026-06-06T15:30:00.000Z",
      title: "Patel Plumbing Supply",
      email: "partners@patelsupply.example",
      businessName: "Patel Plumbing Supply - Newark",
      status: "discovery_scheduled",
      notes: "Referral partner call - co-marketing flyer for trade customers.",
      stripeSessionId: null,
      stripeSubscriptionId: null,
      message: "Discovery call booked · Mon Jun 9 · 2:00 PM ET",
      phone: "(973) 555-6020",
      contact: {
        cellPhone: "(973) 555-6020",
        street: "220 Market Street",
        city: "Newark",
        state: "NJ",
        zip: "07102",
      },
      payload: {
        hasSmsThread: false,
        wdLeadId: null,
      },
      readAt: null,
      inboxFlag: null,
    },
    {
      id: "demo-blog-1",
      source: "blog",
      at: "2026-06-04T12:00:00.000Z",
      title: "5 signs your water heater is failing",
      email: "hello@998webdesigns.com",
      businessName: "998 content engine",
      status: "published",
      notes: null,
      stripeSessionId: null,
      stripeSubscriptionId: null,
      message: "Auto-published local SEO post for Metro Plumbing blog",
      phone: null,
      contact: {},
      payload: {
        url: "https://998webdesigns.com/blog",
        slug: "water-heater-signs",
      },
      readAt: null,
      inboxFlag: null,
    },
  ];

  return items.sort((a, b) => new Date(b.at).getTime() - new Date(a.at).getTime());
}
